name: first CI/CD

on:
  pull_request:
    branches:
      - main

jobs:
  welcome_script:
    runs-on: ubuntu-latest
    steps:
      - name: Welcome part
        run: echo "Hello, guys"
      - name: Get info
        run: |
          echo "Getting comp info ..."
          whoami
          sleep 5
          pwd

  welcome_script_in_parallel:
    runs-on: ubuntu-latest
    steps:
      - name: Welcome part
        run: echo "Hello, guys"
      - name: Get info
        run: |
          echo "Getting comp info ..."
          whoami
          sleep 10
          pwd

  checking:
    needs: [welcome_script,welcome_script_in_parallel]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.10.11, 3.11]
    steps:
      - uses: actions/checkout@v4
